<?php
include 'connection.php';
include 'display-menu.php';
$sql = "SELECT * FROM producten WHERE categorie = 'nacho' ";
$stmt = $conn->prepare($sql);
$stmt->execute();
$products = $stmt->fetchAll();
displayProductsAndCategories($products);
$sql = "SELECT * FROM producten WHERE categorie = 'Taco' ";
$stmt = $conn->prepare($sql);
$stmt->execute();
$products = $stmt->fetchAll();
displayProductsAndCategories($products);
$sql = "SELECT * FROM producten WHERE categorie = 'Ontbijt' ";
$stmt = $conn->prepare($sql);
$stmt->execute();
$products = $stmt->fetchAll();
displayProductsAndCategories($products);
$sql = "SELECT * FROM producten WHERE categorie = 'Drinken' ";
$stmt = $conn->prepare($sql);
$stmt->execute();
$products = $stmt->fetchAll();
displayProductsAndCategories($products);
$sql = "SELECT * FROM producten WHERE categorie = 'Chorros' ";
$stmt = $conn->prepare($sql);
$stmt->execute();
$products = $stmt->fetchAll();
displayProductsAndCategories($products);
$sql = "SELECT * FROM producten WHERE categorie = 'Burrito' ";
$stmt = $conn->prepare($sql);
$stmt->execute();
$products = $stmt->fetchAll();
displayProductsAndCategories($products);
$sql = "SELECT * FROM producten WHERE categorie = 'Vega' ";
$stmt = $conn->prepare($sql);
$stmt->execute();
$products = $stmt->fetchAll();
displayProductsAndCategories($products);